config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create, :show] do
    resources :images, only: [:index, :update]
  end
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favourites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @all_urls = Favourite.where(user_id: params[:user_id]).order(:id)
  end

  def update
    u_id = User.find(params[:user_id])
    img_url = params[:url]
    u_id.favourites.create(url: img_url)
  end
end

app/controllers/users_controller.rb
require 'faker'
require 'net/http'
require 'uri'

class UsersController < ApplicationController
  def index
    @users = User.all


    @urls = []

    20.times do |x|
      faker = Faker::LoremFlickr.image
      first_part = faker.slice"http://loremflickr.com"
      second_part = get_response_with_redirect(URI.parse(faker))
      url = first_part + second_part
      @urls << url
    end
  end

  def get_response_with_redirect(uri)
    r = Net::HTTP.get_response(uri)
    if r.code == "301"
      r = Net::HTTP.get_response(URI.parse(r.header['location']))
      part_url = r.header['location']
    end
    part_url
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_credentials)

    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])

    @urls = []

    20.times do |x|
      faker = Faker::LoremFlickr.image
      first_part = faker.slice"http://loremflickr.com"
      second_part = get_response_with_redirect(URI.parse(faker))
      url = first_part + second_part
      @urls << url
    end
  end

  private
    def user_credentials
      params.require(:user).permit(:name, :lastname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/index.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-success">
  <a class="navbar-brand" href="#">
    <img src="https://cs1.livemaster.ru/storage/42/b3/8091fdf1bf262c6920be8885f84v--kartiny-i-panno-kartina-cheshirskij-kot-pod-zvezdnym-nebom-sve.jpg" width="30" height="30" class="d-inline-block align-top" alt="">
    Bootstrap Homework
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href=<%=users_path%>>Main page</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
  <div class="row">
    <% @all_urls.each do |record|%>
      <div class="col-sm-3">
        <div class="card">
          <div class="container">
            <img class="card-img-top img-fluid image" src=<%= record.url %> alt="image">
            <div class="overlay">
              <div class="text"><%= record.id %></div>
            </div>
          </div>
          <div class="card-block">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootstrapHomework</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<!--<a class="navbar-brand" href="#">-->
<!--  <img src="https://cs1.livemaster.ru/storage/42/b3/8091fdf1bf262c6920be8885f84v--kartiny-i-panno-kartina-cheshirskij-kot-pod-zvezdnym-nebom-sve.jpg" width="30" height="30" class="d-inline-block align-top" alt="">-->
<!--  Bootstrap Homework-->
<!--</a>-->


<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <a class="navbar-brand" href="#">
    <img src="https://cs1.livemaster.ru/storage/42/b3/8091fdf1bf262c6920be8885f84v--kartiny-i-panno-kartina-cheshirskij-kot-pod-zvezdnym-nebom-sve.jpg" width="30" height="30" class="d-inline-block align-top" alt="">
    Bootstrap Homework
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href=<%=new_user_path%>>Create new user</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/users/new.html.erb
<center><h1>Creation of new user</h1></center>

<%= bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-4") do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :lastname %>
  <%= f.email_field :email %>
  <%= f.form_group do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-success">
  <a class="navbar-brand" href="#">
    <img src="https://cs1.livemaster.ru/storage/42/b3/8091fdf1bf262c6920be8885f84v--kartiny-i-panno-kartina-cheshirskij-kot-pod-zvezdnym-nebom-sve.jpg" width="30" height="30" class="d-inline-block align-top" alt="">
    Bootstrap Homework
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href=<%=users_path%>>Main page</a>
          <a class="dropdown-item" href=<%=user_images_path(user_id: @user.id)%>>Show my favourites</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
  <div class="row">
    <% @urls.each do |url|%>
      <div class="col-sm-3">
        <div class="card">
          <div class="container">
            <img class="card-img-top img-fluid image" src=<%= url %> alt="image">
            <div class="overlay">
              <div class="text">Picture ID</div>
            </div>
          </div>
          <div class="card-block">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="card-footer"><center><%= link_to 'Add to favourites', user_image_path(user_id: @user.id, url: url), method: :put, class: "btn btn-success" %></center></div>
        </div>
      </div>
    <% end %>
  </div>
</div>